version: '3.8'
services:
  database:
    image: mariadb:10.5
    container_name: database
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: popo_password
      MYSQL_DATABASE: popo
    command:
      - --character-set-server=utf8mb4 # 한글 인코딩
      - --collation-server=utf8mb4_unicode_ci # 한글 인코딩
  api:
    image: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com/poapper-api:latest
    container_name: popo-api
    ports:
      - "4000:4000"
    depends_on:
      - database
    env_file: 
      - .env.development
