on:
  push:

name: Github Action

env:
  ECR_REGISTRY: 151345152001.dkr.ecr.ap-northeast-2.amazonaws.com
  ECR_REPOSITORY: poapper-api

jobs:
  docker-build-and-push:
    name: Docker build check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker build
        run: docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: AWS ECR push
        run: docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
